name: bmap_map_fluttify_example
description: Demonstrates how to use the bmap_map_fluttify plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  permission_handler: ^4.2.0+hotfix.3
  oktoast: ^2.3.1+1
  decorated_flutter: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bmap_map_fluttify:
    path: ../

flutter:
  uses-material-design: true